"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T11:32:55.716104+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, broadcast, when
from pyspark.sql.types import StringType, FloatType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.option("header", "true")
                      .option("inferSchema", "false")
                       .csv(input_path))
    
    # Add metadata columns
    transactions_df = (transactions_df.withColumn("ingestion_timestamp", lit(run_date))
                      .withColumn("source_file", lit("transactions.csv"))
                       .withColumn("pipeline_run_id", lit(run_id)))

    # Write as Parquet partitioned by date
    transactions_df.write.mode("overwrite").partitionBy("ingestion_timestamp").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.parquet(bronze_path)
                      .where(col("ingestion_timestamp") == run_date))

    # Cast columns to correct types
    transactions_df = (transactions_df.withColumn("amount", col("amount").cast(FloatType()))
                       .withColumn("transaction_date", col("transaction_date").cast(DateType()))
                      .withColumn("transaction_id", col("transaction_id").cast(StringType()))
                      .withColumn("merchant_id", col("merchant_id").cast(StringType())))

    # Filter: remove records where transaction_id is NULL or amount < 0
    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))

    # Read and cache merchants data
    merchants_df = (spark.read.option("header", "true").csv(merchants_path)
                   .withColumn("merchant_id", col("merchant_id").cast(StringType())))
    merchants_df = merchants_df.cache()

    # Deduplicate: if same transaction_id appears twice, keep the record with latest ingestion_timestamp
    transactions_df = (transactions_df.withColumn("rank", 
                             (col("ingestion_timestamp").cast("long")).desc_nulls_last())
                       .filter(col("rank") == 1).drop("rank"))

    # Enrich: join transactions with merchants on merchant_id
    enriched_df = (transactions_df.join(broadcast(merchants_df), "merchant_id", "left")
                  .withColumn("quality_flag", 
                               when(col("merchant_id").isNull(), "UNMATCHED").otherwise("CLEAN")))

    # Write as Parquet partitioned by date
    enriched_df.write.mode("overwrite").partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize Spark session
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())

    # Define paths and run metadata
    # input_path = "s3://sigma-datatech/raw/transactions.csv"
    # merchants_path = "s3://sigma-datatech/raw/merchants.csv"
    # bronze_output_path = "s3://sigma-datatech/bronze/"
    # silver_output_path = "s3://sigma-datatech/silver/"
    # run_date = "2026-05-27"
    # run_id = "run_id_20260527"
    input_path = os.getenv("INPUT_PATH")
    merchants_path = os.getenv("MERCHANTS_PATH")
    bronze_output_path = os.getenv("BRONZE_OUTPUT_PATH")
    silver_output_path = os.getenv("SILVER_OUTPUT_PATH")
    run_date = os.getenv("RUN_DATE")
    run_id = os.getenv("RUN_ID")
   

    # Ingest Bronze layer
    ingest_bronze(spark, input_path, bronze_output_path, run_date, run_id)

    # Transform Silver layer
    transform_silver(spark, f"{bronze_output_path}/ingestion_timestamp={run_date}", 
                      merchants_path, silver_output_path, run_date)

    # Log run metadata summary to a JSON file
    run_metadata = {
        "run_date": run_date,
        "run_id": run_id,
        "input_path": input_path,
        "bronze_output_path": bronze_output_path,
        "silver_output_path": silver_output_path,
        "status": "SUCCESS"
    }

    # with open(f"s3://sigma-datatech/metadata/run_metadata_{run_date}.json", "w") as f:
    #     json.dump(run_metadata, f)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, when, coalesce, mode, collect_set, countDistinct, lit
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate metrics
    merchant_performance_df = (silver_df
       .filter(col("status") == "COMPLETED")
       .groupBy("merchant_id", "merchant_name", "category", "city", "date")
       .agg(
            sum(col("amount")).alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        ))
    
    # Write to output path
    merchant_performance_df.write.mode("overwrite").partitionBy("date").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("status") == "COMPLETED")
    
    # Calculate metrics
    customer_ltv_df = (silver_df
       .groupBy("customer_id")
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            avg("amount").alias("avg_txn_value"),
            min("transaction_date").alias("first_txn_date"),
            max("transaction_date").alias("last_txn_date"),
            mode("payment_method").alias("preferred_payment_method")
        ))
    
    # Write to output path
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate metrics
    daily_summary_df = (silver_df
       .groupBy("date")
       .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(lit(0))).alias("total_revenue"),
            count("*").alias("total_txns"),
            countDistinct("customer_id").alias("unique_customers"),
            countDistinct("merchant_id").alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        ))
    
    # Write to output path
    daily_summary_df.write.mode("overwrite").partitionBy("date").parquet(output_path)

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define output paths
    merchant_performance_output_path = f"{gold_output_dir}/merchant_performance"
    customer_ltv_output_path = f"{gold_output_dir}/customer_ltv"
    daily_summary_output_path = f"{gold_output_dir}/daily_summary"
    
    # Build Gold tables
    build_merchant_performance(spark, silver_path, merchant_performance_output_path, run_date)
    build_customer_ltv(spark, silver_path, customer_ltv_output_path)
    build_daily_summary(spark, silver_path, daily_summary_output_path, run_date)
    
    # Write run metadata summary
    run_metadata = {
        "run_date": run_date,
        "merchant_performance_rows": spark.read.parquet(merchant_performance_output_path).count(),
        "customer_ltv_rows": spark.read.parquet(customer_ltv_output_path).count(),
        "daily_summary_rows": spark.read.parquet(daily_summary_output_path).count()
    }
    
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata.json")

# Initialize Spark session
spark = (SparkSession.builder
        .appName("Sigma DataTech Transaction Analytics Pipeline")
         .getOrCreate())
