"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:57:35.006552+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, coalesce, max as spark_max
from pyspark.sql.types import FloatType, StringType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.format("csv")
                       .option("header", "true")
                       .option("inferSchema", "false")
                        .load(input_path))
    
    # Add metadata columns
    transactions_df = (transactions_df.withColumn("ingestion_timestamp", lit(run_date))
                      .withColumn("source_file", lit("transactions.csv"))
                       .withColumn("pipeline_run_id", lit(run_id)))
    
    # Write as Parquet partitioned by date
    transactions_df.write.partitionBy("ingestion_timestamp").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.format("parquet")
                       .load(bronze_path)
                      .where(col("ingestion_timestamp") == run_date))
    
    # Cast columns to correct types
    transactions_df = (transactions_df.withColumn("amount", col("amount").cast(FloatType()))
                       .withColumn("transaction_date", col("transaction_date").cast(DateType()))
                      .withColumn("transaction_id", col("transaction_id").cast(StringType()))
                       .withColumn("merchant_id", col("merchant_id").cast(StringType())))
    
    # Filter: remove records where transaction_id is NULL or amount < 0
    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    
    # Deduplicate: if same transaction_id appears twice, keep the record with latest ingestion_timestamp
    deduped_transactions_df = (transactions_df.withColumn("rank", 
                        spark_max(col("ingestion_timestamp")).over(window.partitionBy("transaction_id")))
                               .filter(col("rank") == col("ingestion_timestamp"))
                                .drop("rank"))
    
    # Read merchants CSV and cache it
    merchants_df = (spark.read.format("csv")
                   .option("header", "true")
                   .option("inferSchema", "false")
                   .load(merchants_path))
    merchants_df = merchants_df.cache()
    
    # Join with merchants (broadcast hint)
    enriched_transactions_df = (deduped_transactions_df.join(broadcast(merchants_df), 
                                                            deduped_transactions_df.merchant_id == merchants_df.merchant_id, 
                                                            "left_outer"))
    
    # Add quality flag: mark records with no matching merchant as 'UNMATCHED'
    enriched_transactions_df = (enriched_transactions_df.withColumn("quality_flag", 
                                    coalesce(merchants_df.merchant_name, lit("UNMATCHED"))))
    
    # Write as Parquet partitioned by date
    enriched_transactions_df.write.partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize Spark session
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())
    
    # Define paths and run metadata
    input_path = "s3://sigma-datatech-transactions/bronze/"
    bronze_path = "s3://sigma-datatech-transactions/silver/"
    silver_path = "s3://sigma-datatech-transactions/gold/"
    merchants_path = "s3://sigma-datatech-merchants/merchants.csv"
    run_date = "2026-05-27"
    run_id = "run_id_12345"
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, f"{bronze_path}/{run_date}", run_date, run_id)
    
    # Transform Silver layer
    transform_silver(spark, f"{bronze_path}/{run_date}", merchants_path, f"{silver_path}/{run_date}", run_date)
    
    # Write run metadata summary to a JSON file
    metadata = {"run_date": run_date, "run_id": run_id}
    with open(f"s3://sigma-datatech-metadata/run_metadata_{run_date}.json", "w") as f:
        json.dump(metadata, f)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, when, coalesce, avg, collect_set, collect_list, first, last, mode, lit, to_date
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Initialize run metadata
    run_metadata = {
        "run_date": run_date,
        "silver_path": silver_path,
        "gold_output_dir": gold_output_dir,
        "tables": []
    }

    # Build Gold tables
    build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)
    build_customer_ltv(spark, silver_path, f"{gold_output_dir}/customer_ltv")
    build_daily_summary(spark, silver_path, f"{gold_output_dir}/daily_summary", run_date)

    # Write run metadata summary to JSON
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer transactions data
    silver_transactions = spark.read.parquet(silver_path).where(col("date") == run_date)

    # Read Silver layer merchants data and cache it
    silver_merchants = spark.read.parquet(f"{silver_path}/merchants").cache()

    # Join transactions with merchants
    transactions_with_merchants = silver_transactions.join(broadcast(silver_merchants), "merchant_id")

    # Calculate metrics
    merchant_performance = transactions_with_merchants.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
        .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )

    # Write Gold table
    merchant_performance.write.mode("overwrite").partitionBy("date").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer transactions data
    silver_transactions = spark.read.parquet(silver_path)

    # Calculate metrics
    customer_ltv = silver_transactions.filter(col("status") == "COMPLETED") \
        .groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            avg("amount").alias("avg_txn_value"),
            first("transaction_date").alias("first_txn_date"),
            last("transaction_date").alias("last_txn_date"),
            coalesce(mode("payment_method").over(Window.partitionBy("customer_id")), lit(None)).alias("preferred_payment_method")
        )

    # Write Gold table
    customer_ltv.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer transactions data
    silver_transactions = spark.read.parquet(silver_path).where(col("date") == run_date)

    # Calculate metrics
    daily_summary = silver_transactions.groupBy("date") \
        .agg(
            sum(when(col("status") == "COMPLETED", col("amount"))).alias("total_revenue"),
            count("*").alias("total_txns"),
            count(col("customer_id").distinct()).alias("unique_customers"),
            count(col("merchant_id").distinct()).alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )

    # Write Gold table
    daily_summary.write.mode("overwrite").partitionBy("date").parquet(output_path)
