"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:56:00.984843+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, upper, broadcast, when
from pyspark.sql.types import StructType, StructField, StringType, TimestampType, FloatType, IntegerType
import sys

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Define schema for the bronze layer
    bronze_schema = StructType([
        StructField("transaction_id", StringType(), True),
        StructField("merchant_id", StringType(), True),
        StructField("txn_timestamp", StringType(), True),
        StructField("amount", StringType(), True),
        StructField("status", StringType(), True),
        StructField("currency", StringType(), True)
    ])
    
    # Read the input CSV into a DataFrame
    df_bronze = spark.read.option("header", "true").schema(bronze_schema).csv(input_path)
    
    # Add metadata columns
    df_bronze = df_bronze.withColumn("_ingest_ts", lit(run_date)) \
                         .withColumn("_source_file", lit(input_path)) \
                        .withColumn("_batch_date", lit(run_date)) \
                        .withColumn("_pipeline_run_id", lit(run_id))
    
    # Write the DataFrame to the output path partitioned by _batch_date
    df_bronze.write.mode("overwrite").partitionBy("_batch_date").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read the Bronze layer with partition pruning
    df_bronze = spark.read.parquet(bronze_path).where(col("_batch_date") == run_date)
    
    # Cast columns to correct types
    df_bronze = df_bronze.withColumn("txn_timestamp", col("txn_timestamp").cast(TimestampType())) \
                          .withColumn("amount", col("amount").cast(FloatType())) \
                         .withColumn("status", upper(col("status")).cast(StringType()))
    
    # Filter out invalid rows
    df_bronze = df_bronze.filter(
        (col("transaction_id").isNotNull()) &
        (col("merchant_id").isNotNull()) &
        (col("status").isin("SUCCESS", "FAILED")) &
        (col("amount") >= 0)
    )
    
    # Deduplicate based on transaction_id, keeping the latest record
    df_bronze = df_bronze.sortWithinPartitions("transaction_id", "_ingest_ts", ascending=False) \
                          .dropDuplicates(["transaction_id"]) \
                         .sort("transaction_id", "_ingest_ts")
    
    # Read merchants data and broadcast it
    df_merchants = spark.read.parquet(merchants_path)
    df_merchants = broadcast(df_merchants)
    
    # Join with merchants and add quality_flag column
    df_silver = df_bronze.join(df_merchants, "merchant_id", "left")
    df_silver = df_silver.withColumn("quality_flag", when(col("merchant_id").isNotNull(), "CLEAN").otherwise("UNMATCHED"))
    
    # Write the Silver layer partitioned by txn_date
    df_silver.write.mode("overwrite").partitionBy("txn_date").parquet(output_path)

def main():
    # Initialize Spark session
    spark = SparkSession.builder.appName("Merchant Risk Detection Pipeline").getOrCreate()
    
    # Define paths and run date
    input_path = "s3://path/to/bronze/layer"
    bronze_path = "s3://path/to/bronze/layer"
    merchants_path = "s3://path/to/merchants/data"
    output_path = "s3://path/to/silver/layer"
    run_date = "2023-10-01"
    run_id = "run_id_12345"
    
    # Execute bronze and silver layers
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)
    transform_silver(spark, bronze_path, merchants_path, output_path, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, broadcast, expr, sum as _sum, count as _count, max as _max, avg as _avg, mode as _mode, lit, when, date_format, coalesce
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, TimestampType, DecimalType

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Initialize SparkSession
    spark = (SparkSession.builder
            .appName("GoldLayerPipeline")
             .getOrCreate())

    # Load Silver layer data
    silver_df = (spark.read.format("parquet")
                .option("mergeSchema", "true")
                .load(silver_path))

    # Build merchant performance metrics
    merchant_perf_path = f"{gold_output_dir}/merchant_performance"
    build_merchant_performance(spark, silver_df, merchant_perf_path, run_date)

    # Build customer LTV metrics
    customer_ltv_path = f"{gold_output_dir}/customer_ltv"
    build_customer_ltv(spark, silver_df, customer_ltv_path)

    # Build daily summary metrics
    daily_summary_path = f"{gold_output_dir}/daily_summary"
    build_daily_summary(spark, silver_df, daily_summary_path, run_date)

    # Write run metadata to JSON
    run_metadata = {
        "run_date": run_date,
        "merchant_performance_path": merchant_perf_path,
        "customer_ltv_path": customer_ltv_path,
        "daily_summary_path": daily_summary_path
    }
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")

def build_merchant_performance(spark, silver_df, output_path, run_date):
    # Filter for completed transactions
    completed_df = silver_df.filter(col("status") == "SUCCESS")

    # Calculate metrics
    merchant_perf_df = (completed_df.groupBy("merchant_id", date_format(col("txn_timestamp"), "yyyy-MM-dd").alias("date"))
                        .agg(
                            _sum("amount").alias("total_revenue"),
                            _count("*").alias("txn_count"),
                            _count(when(col("status") == "FAILED", 1)).alias("failed_txns")
                        )
                       .withColumn("failure_rate_pct", (col("failed_txns") / col("txn_count") * 100).cast("double"))
                       .select("merchant_id", "date", "total_revenue", "txn_count", "failure_rate_pct"))

    # Write output
    merchant_perf_df.repartition("date").write.partitionBy("date").parquet(output_path)

def build_customer_ltv(spark, silver_df, output_path):
    # Filter for completed transactions
    completed_df = silver_df.filter(col("status") == "SUCCESS")

    # Calculate metrics
    customer_ltv_df = (completed_df.groupBy("customer_id")
                       .agg(
                           _sum("amount").alias("total_spent"),
                           _count("*").alias("total_txns"),
                           _avg("amount").alias("avg_txn_value"),
                           _min(date_format(col("txn_timestamp"), "yyyy-MM-dd")).alias("first_txn_date"),
                           _max(date_format(col("txn_timestamp"), "yyyy-MM-dd")).alias("last_txn_date"),
                           _mode("payment_method").alias("preferred_payment_method")
                       ))

    # Write output
    customer_ltv_df.write.parquet(output_path)

def build_daily_summary(spark, silver_df, output_path, run_date):
    # Calculate metrics
    daily_summary_df = (silver_df.groupBy(date_format(col("txn_timestamp"), "yyyy-MM-dd").alias("date"))
                       .agg(
                            _sum("amount").alias("total_revenue"),
                            _count("*").alias("total_txns"),
                            _countDistinct("customer_id").alias("unique_customers"),
                            _countDistinct("merchant_id").alias("unique_merchants"),
                            _count(when(col("status") == "FAILED", 1)).alias("failed_txns"),
                            ((_count(when(col("status") == "FAILED", 1)) / _count("*")) * 100).alias("failure_rate_pct"))
                        .filter(col("date") == run_date))

    # Write output
    daily_summary_df.repartition("date").write.partitionBy("date").parquet(output_path)
