from typing import Dict, List, Tuple, Union
import pyspark.sql.functions as F
from pyspark.sql import DataFrame

def detect_schema_drift(expected_schema: Dict[str, str], actual_schema: Dict[str, str]) -> Dict[str, Union[Dict[str, str], List[str], Dict[str, Tuple[str, str]], str]]:
    """
    Detects schema drift between expected and actual schemas.

    :param expected_schema: Expected schema as a dictionary
    :param actual_schema: Actual schema as a dictionary
    :return: Drift report with new columns, removed columns, type changes, and drift severity
    """
    new_columns = {k: v for k, v in actual_schema.items() if k not in expected_schema}
    removed_columns = {k: v for k, v in expected_schema.items() if k not in actual_schema}
    type_changes = {k: (expected_schema[k], actual_schema[k]) for k in expected_schema if expected_schema[k]!= actual_schema[k] and k in actual_schema}
    drift_severity = 'NONE'
    if new_columns:
        if any(v!='string' or not (k.endswith('_flag') or k.endswith('_amount')) for k, v in new_columns.items()):
            drift_severity = 'HIGH' if 'int' in [v for v in new_columns.values()] else 'LOW'
        elif any('amount' in k for k in new_columns.keys()):
            drift_severity = 'HIGH'
    return {
        'new_columns': new_columns,
       'removed_columns': list(removed_columns.keys()),
        'type_changes': type_changes,
        'drift_severity': drift_severity
    }

def decide_action(drift_report: Dict[str, Union[Dict[str, str], List[str], Dict[str, Tuple[str, str]], str]]) -> Dict[str, Dict[str, Union[str, str, str]]]:
    """
    Decides the action to take for each column based on the drift report.

    :param drift_report: Drift report generated by detect_schema_drift
    :return: Actions to take for each column
    """
    actions = {}
    for column, dtype in drift_report['new_columns'].items():
        if column.endswith('_flag') or column.endswith('_amount'):
            actions[column] = {'action': 'FLAG_ANOMALY','reason': f'Potential impact on calculations for {column}', 'risk_level': 'HIGH'}
        elif dtype =='string':
            actions[column] = {'action': 'ADD_TO_SCHEMA','reason': 'Safe to add', 'risk_level': 'LOW'}
        else:
            actions[column] = {'action': 'ADD_TO_SCHEMA','reason': 'Type widening is acceptable', 'risk_level': 'LOW'}
    for column in drift_report['removed_columns']:
        actions[column] = {'action': 'HALT','reason': 'Removing columns will break downstream queries', 'risk_level': 'BREAKING'}
    return actions

def apply_schema_evolution(spark_df: DataFrame, decisions: Dict[str, Dict[str, Union[str, str, str]]]) -> Tuple[DataFrame, List[str]]:
    """
    Applies the schema evolution decisions to the DataFrame.

    :param spark_df: Spark DataFrame to apply evolution to
    :param decisions: Actions to take for each column
    :return: Evolved DataFrame and a list of migration notes
    """
    migration_notes = []
    for column, decision in decisions.items():
        if decision['action'] == 'DROP_SILENTLY':
            spark_df = spark_df.drop(column)
        elif decision['action'] == 'FLAG_ANOMALY':
            spark_df = spark_df.withColumn(f'{column}_anomaly_flag', F.lit(True))
            migration_notes.append(f'Added anomaly flag for column {column}')
    return spark_df, migration_notes

def handle_drift(expected_schema: Dict[str, str], actual_schema: Dict[str, str], spark_df: DataFrame = None) -> Dict[str, Union[Dict[str, Union[Dict[str, Dict[str, Union[str, str, str]]], List[str]]], Dict[str, Union[str, List[str], Dict[str, Tuple[str, str]], str]], List[str], Tuple[DataFrame, List[str]]]]:
    """
    Handles schema drift by detecting, deciding, and applying schema evolution.

    :param expected_schema: Expected schema as a dictionary
    :param actual_schema: Actual schema as a dictionary
    :param spark_df: Spark DataFrame to apply evolution to (optional)
    :return: Full evolution report
    """
    drift_report = detect_schema_drift(expected_schema, actual_schema)
    decisions = decide_action(drift_report)
    if spark_df is not None:
        evolved_df, migration_notes = apply_schema_evolution(spark_df, decisions)
    else:
        evolved_df, migration_notes = None, []
    evolution_report = {
        'drift_report': drift_report,
        'decisions': decisions,
        'migration_notes': migration_notes
    }
    if spark_df is not None:
        evolution_report['evolved_df'] = evolved_df
    print(f"Schema Evolution Report: {evolution_report}")
    return evolution_report
